#!/bin/sh
set -e

case "$1" in

    remove)
        # Remove logs
        rm -rf /var/log/chronos
    ;;

    purge)
            # Remove service
        update-rc.d chronos remove >/dev/null || true

        # Remove logs and data
        rm -rf /var/log/chronos

    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
