#!/bin/sh
set -e

if [ -x "/etc/init.d/chronos" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d chronos stop || true
        else
                /etc/init.d/chronos stop || true
        fi
fi
